db-user: cdhzayn
db-pwd: ZAYNsalt66%40
db-password: ZAYNsalt66@
db-server: 1.15.223.250
db-port: 8082

server:
  port: 8080
  servlet:
    context-path: /backend

spring:
  data:
    mongodb:
      username: ${db-user}
      password: ${db-password}

logging:
  level:
    org.springframework.data.mongodb.core: debug